[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana-gpt-oracle = "2TDwskBBb9LafsjZ55UCoCbQn5EYjV3PMDp2eeDD4FqF"
solgpt_vault = "gZAxicCLrgNhFk2f8AZaAxspcDX6PLeymCtGhwmoHpR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
